import type { Metadata } from 'next'
import { Space_Grotesk, IBM_Plex_Sans } from 'next/font/google'
import Layout from '@/components/layout/Layout'
import { CartProvider } from '@/context/CartContext'
import { FavoritesProvider } from '@/context/FavoritesContext'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const spaceGrotesk = Space_Grotesk({
	subsets: ['latin'],
	variable: '--font-space-grotesk',
	weight: ['400', '300', '500', '600', '700']
})

const ibmPlexSans = IBM_Plex_Sans({
	variable: '--font-IBM-plex-sans',
	weight: ['400', '700']
})

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang="en"
			className={`${spaceGrotesk.variable} ${ibmPlexSans.variable}`}
		>
			<head></head>
			<body className={ibmPlexSans.className}>
				<FavoritesProvider>
					<CartProvider>
						<Layout>{children}</Layout>
					</CartProvider>
				</FavoritesProvider>
			</body>
		</html>
	)
}
