import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Layout from '@/components/layout/Layout'
import { CartProvider } from '@/context/CartContext'
import { futuraFont } from '@/lib/fonts'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang="en"
			className={`${futuraFont.variable} ${geistSans.variable} ${geistMono.variable}`}
		>
			<head>
				{/* <link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
				/> */}
			</head>
			<body className={futuraFont.className}>
				<CartProvider>
					<Layout>{children}</Layout>
				</CartProvider>
			</body>
		</html>
	)
}
